version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv sync --group docs
    build:
      html:
        - uv run -- sphinx-build -M html docs $READTHEDOCS_OUTPUT
      pdf:
        - uv run -- sphinx-build -M latexpdf docs $READTHEDOCS_OUTPUT

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - htmlzip
