version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  commands:
    # https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv
    # with adaptations to use workspaces+projects instead of `uv pip`
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync --group docs
    - ./scripts/build-docs

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - htmlzip

conda:
  environment: docs/environment.yml
