version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  commands:
    - uv sync --group docs
    - uv run -- sphinx-build -M html docs $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - htmlzip

conda:
  environment: docs/environment.yml
