version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --group docs
    build:
      html:
        - uv run -- sphinx-build -M html docs $READTHEDOCS_OUTPUT
      pdf:
        - uv run -- sphinx-build -M latexpdf docs $READTHEDOCS_OUTPUT

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - htmlzip
