API  # unused class (/Users/jduckworth/Personal/Code/pystac-api/pystac_api/api.py:12)
root  # unused variable (/Users/jduckworth/Personal/Code/pystac-api/pystac_api/api.py:62)
simple_stac_resolver  # unused function (/Users/jduckworth/Personal/Code/pystac-api/pystac_api/paging.py:20)
paginate  # unused function (/Users/jduckworth/Personal/Code/pystac-api/pystac_api/paging.py:124)
read_text_method  # unused function (/Users/jduckworth/Personal/Code/pystac-api/pystac_api/stac_io.py:6)
