API  # unused class (/Users/jduckworth/Personal/Code/pystac-api/pystac_api/api.py:20)
root  # unused variable (/Users/jduckworth/Personal/Code/pystac-api/pystac_api/api.py:74)
_.search  # unused method (/Users/jduckworth/Personal/Code/pystac-api/pystac_api/api.py:144)
_.current_page  # unused property (/Users/jduckworth/Personal/Code/pystac-api/pystac_api/item_search.py:241)
read_text_method  # unused function (/Users/jduckworth/Personal/Code/pystac-api/pystac_api/stac_io.py:5)
